### ISSUE TITLE
setTag not working

### ISSUE THREAD

**Issue by masoud2v** [mabbas007/TagsEditText#11]
Hi, I want to set Strings as tags but it doesn't work

**Comment by pmrajani** [comment]
Multi TAG is not adding @mabbas007 
i am trying to Add new tags But It's add only one TAG run-time 

```
    for (int i = 0; i < profilelist.size(); i++) {
        tagsEditText.setTags(profilelist.get(i));

    }
```

**Comment by rafaltrzcinski** [comment]
Is there a way to add new tag to existing TagsEditText? If TagsEditText contains some characters, setTags(tags) set all editText's content to this tags.

**Comment by mabbas007** [comment]
@rt90 Unfortunately you will need to set all the tags all over again

**Comment by mabbas007** [comment]
@pmrajani setTags takes an array of strings or CharSequence, not string by string
