### ISSUE TITLE
Failing to import Dependency via gradle

### ISSUE THREAD

**Issue by larrytech7** [mabbas007/TagsEditText#14]
I can't seem to import the library using gradle 
    compile 'com.github.mabbas007:TagsEditText:v1.0.1'

**Comment by larrytech7** [comment]
Even when i add the @aar qualifier, it still fails to resolve properly

**Comment by mabbas007** [comment]
Don't forget to add the following

allprojects {
        repositories {
            maven { url "https://jitpack.io" }
        }
    }

**Comment by larrytech7** [comment]
I've added and no change.same issue

**Comment by larrytech7** [comment]
It now works thanks @mabbas007 . But why do i have to use the tag above when i am already using the jitpack repositories in the project wide build.gradle?

**Comment by mabbas007** [comment]
Glad to hear that, I'm not sure why.
