### ISSUE TITLE
How to create tag when user types ',' (comma) key

### ISSUE THREAD

**Issue by aldakur** [mabbas007/TagsEditText#19]
When the user is typing a new item (that isn't in fruits.xml) and pushes the enter key the tag is created. I want the same but when the user types ',' (comma) key.

I'm reading the code but I don't found that code.

**Comment by mabbas007** [comment]
This could be an enhancement to give the library user the option set a custom separator instead of spaces of enter key

**Comment by aldakur** [comment]
I can try develop it but I'm not sure how to do it. So, so the enter key function is by default? It wasn't developed by you?

**Comment by SaffireCoder** [comment]
in TagsEditText there's SEPARATOR = "  ". Fork it and change it to ","

**Comment by FrancisMG** [comment]
I think this is issue is not close. Im having the same scenario here. The separator only does separated the created tag. The problem here is that , create a tag when user click ','
