### ISSUE TITLE
How am I suposed to get A List os tags?

### ISSUE THREAD

**Issue by AnaxAndrade** [mabbas007/TagsEditText#28]
Can't figure out how to get List<String> of tags - not from an event, but synchronously at any time. Like a 
public List<String> getTags() method on the TagsEditText?

**Comment by mabbas007** [comment]
I'll mark this as enhancement, and work on it asap

**Comment by AnaxAndrade** [comment]
Just Add:
```
public List<String> getTags(){
        return convertTagSpanToList(mTagSpans);
    }
```
To the File TagsEditText.java

PS: I wanted to make a Pull Request but after opening this repo on Android Studio couldn't get gradle to Sync because of (but no problem since yo just will have those 3 lines above): 

> Error:org.gradle.api.internal.tasks.DefaultTaskInputs$TaskInputUnionFileCollection cannot be cast to org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection
> Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

**Comment by AnaxAndrade** [comment]
@mabbas007 Any updates on this?

**Comment by aleporf** [comment]
... any updates i want to get a list<String>

**Comment by mabbas007** [comment]
Working on it, will push it in a couple of minutes
