### ISSUE TITLE
LIMIT TAGS

### ISSUE THREAD

**Issue by aleporf** [mabbas007/TagsEditText#34]
How to set max tags inserted?

**Comment by Pirksy** [comment]
@Override
    public void onTagsChanged(Collection<String> collection) {
        handleLimit(edFieldTag.getText().length(), collection.size());
    }

    @Override
    public void onEditingFinished() {

    }

    private void handleLimit(int currentTextLength, int currentTagsCount) {
        int length = (maxTags <= currentTagsCount) ? currentTextLength : Integer.MAX_VALUE;
        edFieldTag.setFilters(new InputFilter[]{new InputFilter.LengthFilter(length)});
    }
