### ISSUE TITLE
Max Tags and Background error

### ISSUE THREAD

**Issue by andrestorres123** [mabbas007/TagsEditText#8]
the tagsBackground property is making the app crash whenever any value is set. 

Is there a way to set a maximum number of tags permitted? Is there a way to set the Edit Text as single line? (the default attribute is not working)

Thanks

**Comment by mabbas007** [comment]
Could you try set the tagsBackground from code at the moment until I've some time to investigate the issue.

**Comment by andrestorres123** [comment]
Same issue from code. I can wait.
